version: '3'

services:
    app:
        build: ./
        container_name: app
        working_dir: /home/www
        volumes:
            - ./:/home/www
    redis:
        image: redis:7.4-alpine
        container_name: redis
        ports:
            - '6379:6379'
